file_format: "1.0-rc.3"

tracer_provider:
  processors:
    - simple:
        exporter:
          console:
  tracer_configurator/development:
    # SNIPPET_START
    default_config:
      disabled: true
    tracers:
      - name: io.opentelemetry.contrib.*
        config:
          disabled: false