file_format: "1.0-rc.3"

logger_provider:
  processors:
    - simple:
        exporter:
          console:
  logger_configurator/development:
    # SNIPPET_START
    default_config:
      disabled: true
    loggers:
      - name: io.opentelemetry.contrib.*
        config:
          disabled: false
          minimum_severity: info
          trace_based: true
