file_format: "1.0-rc.3"

meter_provider:
  readers:
    - pull:
        exporter:
          prometheus/development:
            # SNIPPET_START
            host: localhost
            port: 9464
            without_scope_info: false
            without_target_info: false
            with_resource_constant_labels:
              included:
                - "service*"
              excluded:
                - "service.attr1"
            translation_strategy: underscore_escaping_with_suffixes