file_format: "1.0-rc.3"

meter_provider:
  readers:
    - periodic:
        exporter:
          console:
  meter_configurator/development:
    # SNIPPET_START
    default_config:
      disabled: true
    meters:
      - name: io.opentelemetry.contrib.*
        config:
          disabled: false