timeout = 30
retry_wait_time = 5
max_retries = 6
max_concurrency = 4

# Check link anchors
include_fragments = true

accept = ["200..=299", "403"]

exclude = [
    # excluding links to pull requests and issues is done for performance
    '^https://github.com/open-telemetry/opentelemetry-configuration/(issues|pull)/\d+$',
    # exclude localhost, file references from schema-docs.md
    "^http://localhost",
    "file:///path/to/file.jsonl",
    "file:///var/log/logs.jsonl",
    "file:///var/log/metrics.jsonl",
    "file:///var/log/traces.jsonl",
]
