title: OpenTelemetryConfiguration
type: object
additionalProperties: true
properties:
  file_format:
    type: string
  disabled:
    type:
      - boolean
      - "null"
  log_level:
    type:
      - string
      - "null"
  attribute_limits:
    $ref: "#/$defs/AttributeLimits"
  logger_provider:
    $ref: "#/$defs/LoggerProvider"
  meter_provider:
    $ref: "#/$defs/MeterProvider"
  propagator:
    $ref: "#/$defs/Propagator"
  tracer_provider:
    $ref: "#/$defs/TracerProvider"
  resource:
    $ref: "#/$defs/Resource"
  instrumentation/development:
    $ref: "#/$defs/ExperimentalInstrumentation"
required:
  - file_format
$defs:
  AttributeLimits:
    type: object
    additionalProperties: false
    properties:
      attribute_value_length_limit:
        type:
          - integer
          - "null"
        minimum: 0
      attribute_count_limit:
        type:
          - integer
          - "null"
        minimum: 0
  LoggerProvider:
    $ref: logger_provider.yaml
  MeterProvider:
    $ref: meter_provider.yaml
  TracerProvider:
    $ref: tracer_provider.yaml
  Propagator:
    $ref: propagator.yaml
  Resource:
    $ref: resource.yaml
  ExperimentalInstrumentation:
    $ref: instrumentation.yaml
