title: OpenTelemetryConfiguration
type: object
additionalProperties: true
properties:
  file_format:
    type: string
    description: |
      The file format version.
      The yaml format is documented at
      https://github.com/open-telemetry/opentelemetry-configuration/tree/main/schema
  disabled:
    type:
      - boolean
      - "null"
    description: |
      Configure if the SDK is disabled or not.
      If omitted or null, false is used.
  log_level:
    type:
      - string
      - "null"
    description: |
      Configure the log level of the internal logger used by the SDK.
      If omitted, info is used.
  attribute_limits:
    $ref: "#/$defs/AttributeLimits"
    description: |
      Configure general attribute limits. See also tracer_provider.limits, logger_provider.limits.
  logger_provider:
    $ref: "#/$defs/LoggerProvider"
    description: |
      Configure logger provider.
      If omitted, a noop logger provider is used.
  meter_provider:
    $ref: "#/$defs/MeterProvider"
    description: |
      Configure meter provider.
      If omitted, a noop meter provider is used.
  propagator:
    $ref: "#/$defs/Propagator"
    description: |
      Configure text map context propagators.
      If omitted, a noop propagator is used.
  tracer_provider:
    $ref: "#/$defs/TracerProvider"
    description: |
      Configure tracer provider.
      If omitted, a noop tracer provider is used.
  resource:
    $ref: "#/$defs/Resource"
    description: |
      Configure resource for all signals.
      If omitted, the default resource is used.
  instrumentation/development:
    $ref: "#/$defs/ExperimentalInstrumentation"
    description: |
      Configure instrumentation.
required:
  - file_format
$defs:
  AttributeLimits:
    type: object
    additionalProperties: false
    properties:
      attribute_value_length_limit:
        type:
          - integer
          - "null"
        minimum: 0
        description: |
          Configure max attribute value size. 
          Value must be non-negative.
          If omitted or null, there is no limit.
      attribute_count_limit:
        type:
          - integer
          - "null"
        minimum: 0
        description: |
          Configure max attribute count. 
          Value must be non-negative.
          If omitted or null, 128 is used.
  LoggerProvider:
    $ref: logger_provider.yaml
  MeterProvider:
    $ref: meter_provider.yaml
  TracerProvider:
    $ref: tracer_provider.yaml
  Propagator:
    $ref: propagator.yaml
  Resource:
    $ref: resource.yaml
  ExperimentalInstrumentation:
    $ref: instrumentation.yaml
